#!/bin/sh
make install

rm *.o

for i in cg.c decl.c expr.c gen.c main.c misc.c \
        opt.c scan.c stmt.c sym.c tree.c types.c
do echo "./cwj -c -g $i"; ./cwj -c $i ;# ./cwj -S $i
done

cc -g  -o comp_src cg.o decl.o expr.o gen.o main.o misc.o \
        opt.o scan.o stmt.o sym.o tree.o types.o

rm *.o
