#!/bin/bash
set -e
set -x

# Build the 6809 compiler binaries. Also create front-end shell scripts
# so that we can run them as if they were native programs.
# Do this twice to run the triple test on the 6809 compiler binaries.

# Use local wcc if available
WCC=./wcc
if [ ! -x "$WCC" ]; then
  echo "Error: wcc not found or not executable. Run 'make wcc' or 'make install' first."
  exit 1
fi

# === Build L1 binaries ===
mkdir -p L1

# Build the compiler itself (using ./wcc)
$WCC -o L1/wcc wcc.c

# Build other tools
cc -o L1/cpeep cpeep.c
./wcc -m6809 -o L1/_cscan scan.c misc.c
./wcc -m6809 -o L1/_detok detok.c tstring.c
./wcc -m6809 -o L1/_detree -DDETREE detree.c misc.c tree.c
./wcc -m6809 -o L1/_desym desym.c
./wcc -m6809 -o L1/_cparse6809 -DWRITESYMS decl.c expr.c misc.c opt.c \
                parse.c stmt.c sym.c tree.c targ6809.c tstring.c types.c
./wcc -m6809 -o L1/_cgen6809 -DSPLITSWITCH cg6809.c cgen.c gen.c misc.c sym.c \
                targ6809.c tree.c types.c

# Make the front-end shell scripts for L1
L1DIR=$(pwd)/L1
for i in cscan detok detree desym cparse6809 cgen6809; do
  cat << EOF > L1/$i
#!/bin/sh
exec emu6809 $L1DIR/_$i "\$@"
EOF
  chmod +x L1/$i
done

# === Build L2 binaries ===
make l2dirs.h

mkdir -p L2

# Build compiler and tools for L2 (using L1/wcc)
L1WCC=L1/wcc

$L1WCC -o L2/wcc wcc.c
cc -o L2/cpeep cpeep.c
$L1WCC -m6809 -v -o L2/_cscan scan.c misc.c
$L1WCC -m6809 -v -o L2/_detok detok.c tstring.c
$L1WCC -m6809 -v -o L2/_detree -DDETREE detree.c misc.c tree.c
$L1WCC -m6809 -v -o L2/_desym desym.c
$L1WCC -m6809 -v -o L2/_cparse6809 -DWRITESYMS decl.c expr.c misc.c opt.c \
                        parse.c stmt.c sym.c tree.c targ6809.c tstring.c types.c
$L1WCC -m6809 -v -o L2/_cgen6809 -DSPLITSWITCH cg6809.c cgen.c gen.c misc.c sym.c \
                        targ6809.c tree.c types.c

#rm -f l2dirs.h dirs.h

# Make the front-end shell scripts for L2
L2DIR=$(pwd)/L2
for i in cscan detok detree desym cparse6809 cgen6809; do
  cat << EOF > L2/$i
#!/bin/sh
exec emu6809 $L2DIR/_$i "\$@"
EOF
  chmod +x L2/$i
done

exit 0
